gripper_node:
  ros__parameters:
    robot_ns: dsr01
    robot_ip: "110.120.1.40"
    command_transport: tcp
    tcp_external_server: false
    robot_port: 9105
    tcp_protocol: json
    gripper_command_action_enabled: false
    direct_cmd_topic_enabled: false
    tcp_state_stream_enabled: true
    tcp_state_hz: 10.0
    state_hz: 10.0
    drl_snap_enabled: false
    plc_feedback_enabled: false

gripper_joint_state:
  ros__parameters:
    gripper_state_topic: /gripper/state
    joint_states_topic: /joint_states
    open_rad: 0.0
    closed_rad: 1.101
    pulse_open: 0
    pulse_closed: 700
    publish_hz: 20.0
    poll_gripper_service: true
